argo-cd:

  global:
    domain: argocd.local

  configs:
    params:
      server.insecure: true

  server:

    service:
      type: ClusterIP

    ingress:
      enabled: true

      ingressClassName: public

      hostname: argocd.local

      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTP

  redis:
    enabled: true

  dex:
    enabled: true

  notifications:
    enabled: false

  applicationSet:
    enabled: true